### model
model_name_or_path: /path/to/Qwen2-7B-Instruct
adapter_name_or_path: data/trained_models/fullm

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
eval_dataset: follow_up_data_test_aug_f3_demo
template: qwen
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: data/trained_models/follow_up_data_test_aug_f3_demo
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
ddp_timeout: 180000000