### model
model_name_or_path: /path/to/model
adapter_name_or_path: /path/to/adapter

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
eval_dataset: <fold_eval_dataset>
template: qwen
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /path/to/output/dir/predict
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
ddp_timeout: 180000000 