#!/usr/bin/env bash
set -euo pipefail
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5
REPO_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
DATA_DIR="$REPO_ROOT/data"
TS="$(date +%Y%m%d_%H%M%S)"
LOG_DIR="$REPO_ROOT/logs/train_predict_$TS"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/run.log"

echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f1.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f1.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f1_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f1_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f2.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f2.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f2_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f2_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f3.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f3.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f3_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f3_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f4.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f4.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f4_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f4_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f5.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f5.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/aug/qwen2_lora_sft_aug_f5_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/aug/qwen2_lora_sft_aug_f5_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f1.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f1.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f1_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f1_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f2.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f2.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f2_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f2_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f3.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f3.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f3_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f3_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f4.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f4.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f4_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f4_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f5.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f5.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
echo "Run: config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f5_predict.yaml" | tee -a "$LOG_FILE"
llamafactory-cli train "config/train_predict/wo_aug/qwen2_lora_sft_wo_aug_f5_predict.yaml" 2>&1 | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
